server:
  port: 8080

spring:
  application:
    name: order
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true

